dist: xenial
language: python

python:
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION='Django~=2.2.0' DRF_VERSION='djangorestframework~=3.9.0'
  - DJANGO_VERSION='Django~=2.2.0' DRF_VERSION='djangorestframework~=3.10.0'
  - DJANGO_VERSION='Django~=2.2.0' DRF_VERSION='djangorestframework~=3.11.0'
  - DJANGO_VERSION='Django~=3.0.0' DRF_VERSION='djangorestframework~=3.10.0'
  - DJANGO_VERSION='Django~=3.0.0' DRF_VERSION='djangorestframework~=3.11.0'

before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install:
  - poetry install
  - pip install -U "$DJANGO_VERSION"
  - pip install -U "$DRF_VERSION"

script:
  - make style-check
  - make test-cov

after_success:
  - pip install codecov
  - codecov

before_deploy:
  - poetry config http-basic.pypi $SECURE_USER $SECURE_PASSWORD
  - poetry build

deploy:
  provider: script
  script: poetry publish
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = 3.7 && $DJANGO_VERSION ~= ^3.0 && $DRF_VERSION ~= ^3.11

notifications:
  email:
    on_success: never
    on_failure: change