dist: xenial
language: python

python:
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION='Django~=2.2.0' DRF_VERSION='djangorestframework~=3.10.0'
  - DJANGO_VERSION='Django~=2.2.0' DRF_VERSION='djangorestframework~=3.11.0'
  - DJANGO_VERSION='Django~=2.2.0' DRF_VERSION='djangorestframework~=3.12.0'
  - DJANGO_VERSION='Django~=3.0.0' DRF_VERSION='djangorestframework~=3.10.0'
  - DJANGO_VERSION='Django~=3.0.0' DRF_VERSION='djangorestframework~=3.11.0'
  - DJANGO_VERSION='Django~=3.0.0' DRF_VERSION='djangorestframework~=3.12.0'
  - DJANGO_VERSION='Django~=3.1.0' DRF_VERSION='djangorestframework~=3.10.0'
  - DJANGO_VERSION='Django~=3.1.0' DRF_VERSION='djangorestframework~=3.11.0'
  - DJANGO_VERSION='Django~=3.1.0' DRF_VERSION='djangorestframework~=3.12.0'

before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install:
  - poetry install
  - pip install -U "$DJANGO_VERSION"
  - pip install -U "$DRF_VERSION"

script:
  - make style-check
  - make test-cov

after_success:
  - pip install codecov
  - codecov

notifications:
  email:
    on_success: never
    on_failure: change