---
name: Publish to PyPI

on:
  release:
    types:
      - released

jobs:
  publish:
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10']
        poetry-version: ['1.3.2']
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Build and publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build --no-interaction