---
name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}, DRF ${{ matrix.drf-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        poetry-version: ['1.3.2']
        django-version: ['3.2.18', '4.1', '4.2']
        drf-version: ['3.12', '3.14']

    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Upgrade django version
        run: |
          poetry run pip install "Django==${{ matrix.django-version }}"
      - name: Upgrade drf version
        run: |
          poetry run pip install "djangorestframework==${{ matrix.drf-version }}"
      - name: Run style checks
        run: make style-check
      - name: Run tests
        run: make test-cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true